// Code generated by protoc-gen-go.
// source: site.proto
// DO NOT EDIT!

/*
Package site is a generated protocol buffer package.

It is generated from these files:
	site.proto

It has these top-level messages:
	RegisterCall
	LoginCall
	InfoCall
	User
*/
package site

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterCall struct {
	User            *User  `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Password        string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	PasswordConfirm string `protobuf:"bytes,3,opt,name=password_confirm,json=passwordConfirm" json:"password_confirm,omitempty"`
}

func (m *RegisterCall) Reset()                    { *m = RegisterCall{} }
func (m *RegisterCall) String() string            { return proto.CompactTextString(m) }
func (*RegisterCall) ProtoMessage()               {}
func (*RegisterCall) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegisterCall) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *RegisterCall) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterCall) GetPasswordConfirm() string {
	if m != nil {
		return m.PasswordConfirm
	}
	return ""
}

type LoginCall struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginCall) Reset()                    { *m = LoginCall{} }
func (m *LoginCall) String() string            { return proto.CompactTextString(m) }
func (*LoginCall) ProtoMessage()               {}
func (*LoginCall) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginCall) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginCall) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type InfoCall struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *InfoCall) Reset()                    { *m = InfoCall{} }
func (m *InfoCall) String() string            { return proto.CompactTextString(m) }
func (*InfoCall) ProtoMessage()               {}
func (*InfoCall) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *InfoCall) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type User struct {
	Username      string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Email         string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	IsAdmin       bool   `protobuf:"varint,3,opt,name=is_admin,json=isAdmin" json:"is_admin,omitempty"`
	IsDj          bool   `protobuf:"varint,4,opt,name=is_dj,json=isDj" json:"is_dj,omitempty"`
	TwitterHandle string `protobuf:"bytes,5,opt,name=twitter_handle,json=twitterHandle" json:"twitter_handle,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *User) GetIsDj() bool {
	if m != nil {
		return m.IsDj
	}
	return false
}

func (m *User) GetTwitterHandle() string {
	if m != nil {
		return m.TwitterHandle
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterCall)(nil), "RegisterCall")
	proto.RegisterType((*LoginCall)(nil), "LoginCall")
	proto.RegisterType((*InfoCall)(nil), "InfoCall")
	proto.RegisterType((*User)(nil), "User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Users service

type UsersClient interface {
	Register(ctx context.Context, in *RegisterCall, opts ...grpc.CallOption) (*User, error)
	Login(ctx context.Context, in *LoginCall, opts ...grpc.CallOption) (*User, error)
	Info(ctx context.Context, in *InfoCall, opts ...grpc.CallOption) (*User, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) Register(ctx context.Context, in *RegisterCall, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/Users/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Login(ctx context.Context, in *LoginCall, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/Users/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Info(ctx context.Context, in *InfoCall, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/Users/Info", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Users service

type UsersServer interface {
	Register(context.Context, *RegisterCall) (*User, error)
	Login(context.Context, *LoginCall) (*User, error)
	Info(context.Context, *InfoCall) (*User, error)
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Users/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Register(ctx, req.(*RegisterCall))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginCall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Users/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Login(ctx, req.(*LoginCall))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoCall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Users/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Info(ctx, req.(*InfoCall))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Users_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Users_Login_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Users_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "site.proto",
}

func init() { proto.RegisterFile("site.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x41, 0x4e, 0xeb, 0x30,
	0x10, 0x55, 0xfa, 0x93, 0xff, 0x93, 0xf9, 0x14, 0x90, 0x5b, 0x50, 0x1a, 0x10, 0xaa, 0x22, 0x81,
	0xca, 0x26, 0x11, 0x05, 0x89, 0x2d, 0xa8, 0x2c, 0x40, 0x62, 0x15, 0xa9, 0xeb, 0xc8, 0x10, 0x37,
	0xb8, 0x4a, 0xec, 0xc8, 0x36, 0x74, 0xcf, 0x05, 0x58, 0x70, 0x19, 0xee, 0xc1, 0x15, 0x38, 0x08,
	0xca, 0xa4, 0xa9, 0xe8, 0x02, 0xd8, 0xf9, 0x3d, 0xcf, 0x9b, 0x37, 0x7e, 0x63, 0x00, 0xcd, 0x0d,
	0x8b, 0x2a, 0x25, 0x8d, 0x0c, 0xf6, 0x73, 0x29, 0xf3, 0x82, 0xc5, 0xb4, 0xe2, 0x31, 0x15, 0x42,
	0x1a, 0x6a, 0xb8, 0x14, 0xba, 0xb9, 0x0d, 0x2b, 0xd8, 0x48, 0x58, 0xce, 0xb5, 0x61, 0x6a, 0x42,
	0x8b, 0x82, 0x0c, 0xc0, 0x7e, 0xd4, 0x4c, 0xf9, 0xd6, 0xd0, 0x1a, 0xfd, 0x1f, 0x3b, 0xd1, 0x54,
	0x33, 0x95, 0x20, 0x45, 0x02, 0x70, 0x2b, 0xaa, 0xf5, 0x42, 0xaa, 0xcc, 0xef, 0x0c, 0xad, 0x91,
	0x97, 0xac, 0x30, 0x39, 0x86, 0xed, 0xf6, 0x9c, 0xde, 0x4b, 0x31, 0xe3, 0xaa, 0xf4, 0xff, 0x60,
	0xcd, 0x56, 0xcb, 0x4f, 0x1a, 0x3a, 0x9c, 0x80, 0x77, 0x2b, 0x73, 0x2e, 0xd0, 0x2e, 0x00, 0xb7,
	0xee, 0x2d, 0x68, 0xc9, 0xd0, 0xd2, 0x4b, 0x56, 0xf8, 0x27, 0xbf, 0xf0, 0x08, 0xdc, 0x1b, 0x31,
	0x93, 0xbf, 0xf5, 0x08, 0x5f, 0x2c, 0xb0, 0xa7, 0xcb, 0xe1, 0xbf, 0x35, 0xea, 0x83, 0xc3, 0x4a,
	0xca, 0x8b, 0xa5, 0x4b, 0x03, 0xc8, 0x00, 0x5c, 0xae, 0x53, 0x9a, 0x95, 0x5c, 0xe0, 0x53, 0xdc,
	0xe4, 0x1f, 0xd7, 0x97, 0x35, 0x24, 0x3d, 0x70, 0xb8, 0x4e, 0xb3, 0xb9, 0x6f, 0x23, 0x6f, 0x73,
	0x7d, 0x35, 0x27, 0x87, 0xb0, 0x69, 0x16, 0xdc, 0x18, 0xa6, 0xd2, 0x07, 0x2a, 0xb2, 0x82, 0xf9,
	0x0e, 0xb6, 0xeb, 0x2e, 0xd9, 0x6b, 0x24, 0xc7, 0x6f, 0x16, 0x38, 0xf5, 0x44, 0x9a, 0x5c, 0x80,
	0xdb, 0x46, 0x4f, 0xba, 0xd1, 0xd7, 0x2d, 0x04, 0x4d, 0xee, 0xe1, 0xc1, 0xf3, 0xfb, 0xc7, 0x6b,
	0xc7, 0x0f, 0x77, 0xe3, 0xa7, 0x13, 0xdc, 0x5f, 0x3d, 0xb2, 0x8e, 0x55, 0xab, 0x3a, 0x07, 0x07,
	0xa3, 0x24, 0x10, 0xad, 0x22, 0x6d, 0xb5, 0x7b, 0xa8, 0xdd, 0x09, 0x7b, 0xeb, 0xda, 0x02, 0xeb,
	0xcf, 0xc0, 0xae, 0xe3, 0x23, 0x5e, 0xd4, 0xa6, 0xd8, 0xca, 0x02, 0x94, 0xf5, 0x09, 0x59, 0x97,
	0x71, 0x31, 0x93, 0x77, 0x7f, 0xf1, 0xcb, 0x9c, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x6f,
	0xae, 0x99, 0x5e, 0x02, 0x00, 0x00,
}
